### ISSUE TITLE
Paylink endpoints are incorrect on the README.md

### ISSUE THREAD

**Issue by jcote-awh** [PayLink/APIs#2]
Endpoints shown should be the same as in the curl examples:
https://www.payfabric.com/V2/rest/api/help will return available commands.

The following URLs work. 
1.  LIVE: https://www.payfabric.com/V2/rest/api/
2. SANDBOX: https://sandbox.payfabric.com/V2/rest/api

**Comment by ShaunSharples** [comment]
Hi John,

That you very much for pointing this out.  We are sorry if this caused you any confusion, I will update these now.

**Comment by ShaunSharples** [comment]
This issue is resolved now.  Just so are aware John, the actual URL's for our PayLink service is:
Live: https://www.payfabric.com/v2/PayLink
Sandbox: https://sandbox.payfabric.com/v2/PayLink

As shown here: https://sandbox.payfabric.com/v2/PayLink/help
